dist: trusty
sudo: require

language: cpp
compiler: clang++

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - clang-5.0
      - cmake-data
      - cmake
      - python3
      - python3-dev
      - python3-venv
      - python3-pip

matrix:
  include:
    # works on Trusty
    - os: linux
      env: PYTHON=3.5
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
    - eval "${MATRIX_EVAL}"
    - pyenv global $(pyenv whence 2to3) 
    - pip3 install --user --upgrade pip virtualenv
    - virtualenv -p python3 venv
    - source venv/bin/activate


install:
    - pip3 install pybind11

script:
  - CXX=/usr/bin/clang++-5.0

  - cd ${TRAVIS_BUILD_DIR}/Software/Firmware/
  - bash dependencies.sh 
  - mkdir build
  - cd ./build
  - cmake -DCMAKE_BUILD_TYPE=Debug ../
  - make all -j
  - ctest --output-on-failure
  - make clean
  - cmake -DCMAKE_BUILD_TYPE=Release ../
  
  - make all -j
